[package]
name = "utwallet"
version = "0.0.1"
authors = ["Richard Ulrich <richi+utwallet@ulrichard.ch>"]
edition = "2018"
build = "src/build.rs"

[dependencies]
qmetaobject = "0.2.3"
qt_core = "0.5.0"
gettext-rs = "0.7"
cstr = "0.2.8"
cpp = "0.5"
bdk = { version = "0.23", features = ["electrum", "key-value-db", "all-keys"] }
serde = "1.0.147"
serde_json = "1.0.87"
qrcode-png = "0.4"
chrono = "0.4"

[build-dependencies]
cpp_build = "0.5"
