[package]
name = "utwallet"
version = "0.0.5"
authors = ["Richard Ulrich <richi+utwallet@ulrichard.ch>"]
edition = "2021"
build = "src/build.rs"

[dependencies]
qmetaobject = "0.2.3"
qt_core = "0.5.0"
gettext-rs = "0.7"
cstr = "0.2.8"
cpp = "0.5"
#bdk = { version = "0.28", features = ["electrum", "key-value-db", "all-keys"] }
bdk = { version = "0.28", default-features = false, features = ["std", "use-esplora-async", "key-value-db", "all-keys"] }
ldk-node = "0.1.0-alpha"
serde = "1.0.147"
serde_json = "1.0.87"
qrcode-png = "0.4"
chrono = "0.4"
regex = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
cpp_build = "0.5"
cmake = "0.1"
